server:
  port: 8001
  servlet:
    context-path: /producer

spring:
  application:
    name: producer
  cloud:
    stream:
      binders:
        output_channel:
          destination: exchange-3
          group: queue-3
          binder: rabbit_cluster
        rabbit_cluster:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 192.168.1.140:5672
                username: guest
                password: guest
                virtual-host: /