server:
  port: 8002
  servlet:
    context-path: /consumer 
 
spring:
  application:
    name: consumer
  cloud:
    stream:
      binders: 
        input_channel: 
          destination: exchange-3
          group: queue-3
          binder: rabbit_cluster
          consumer:
            concurrency: 1
        rabbit_cluster:
          environment:
            spring:
              rabbitmq:
                addresses: 192.168.11.76:5672
                username: guest
                password: guest
                virtual-host: /
      rabbit:
        bindings:
          input_channel: 
            consumer: 
              requeue-rejected: false
              acknowledge-mode: MANUAL
              recovery-interval: 3000
              durable-subscription: true
              max-concurrency: 5